version: '3.8'
services:
  aptly:
    build:
        context: .
        dockerfile: Dockerfile
    image: ai-writing-assistant
    container_name: ai-assistant
    environment:
      - OPENAI_API_KEY=""
    ports:
      - 3000:3000

