version: '3.8'
services:
  ai-writing-assistant:
    build:
        context: .
        dockerfile: Dockerfile
    image: ai-writing-assistant
    container_name: ai-assistant
    environment:
      OPENAI_API_KEY: "sk-fWY75n1TMkS76PBT3BlbkFJiY0HoJrRGNMd2x46AfqX"
    ports:
      - 3001:3000

